### ISSUE TITLE
Fails to read last page

### ISSUE THREAD

**Issue by callistino** [Rxnet/eventstore-client#16]
Reading from the store using `\Rxnet\EventStore\EventStore::readEventsForward` fails to read the last page of events. I've narrowed it down to this method `\Rxnet\EventStore\EventStore::readEvents`. Specifically the observable's `takeWhile`. This method exits as soon as the stream reaches the end or if it has read the total count of events  requested and exists without passing forward the current set of events if any. This happens even if the last page of event is the first page. So if you have less than 10 events it will not read any.

I've prepared an example:

1. Run `php examples/write.php`. Take note of the last event written or connect to the web ui at [localhost:2113](localhost:2113).
2. Copy the snippet below to *examples/readForward.php*.
3. Run `php examples/readForward.php`
4. See the last "received" event is either 10 less than the total available or none if the total is less than 10.

```php
<?php

use EventLoop\EventLoop;

require __DIR__.'/../vendor/autoload.php';


$eventStore = new \Rxnet\EventStore\EventStore();
$eventStore->connect()
    ->subscribe(function() use ($eventStore) {
        echo "connected \n";
        $eventStore->readEventsForward('domain-test.fr')
            ->subscribe(function (\Rxnet\EventStore\EventRecord $record) {
                echo "received {$record->getId()}  {$record->getNumber()}@{$record->getStreamId()} {$record->getType()} created at {$record->getCreated()->format('c')}\n";
            });
    }, function (\Exception $e) {
        echo $e->getMessage();
    });

EventLoop::getLoop()->run();
```

Below is a very crude possible fix I've implemented. I've researched and I haven't found a better way to use observable operators instead of using flags. 

```bash
diff --git a/src/Rxnet/EventStore/EventStore.php b/src/Rxnet/EventStore/EventStore.php
index 48f0a89..4243af5 100644
--- a/src/Rxnet/EventStore/EventStore.php
+++ b/src/Rxnet/EventStore/EventStore.php
@@ -538,6 +538,7 @@ class EventStore
         // OnDemand ? onBackpressureBuffer ?
         return Observable::create(function (ObserverInterface $observer) use ($messageType, $query) {
             $end = false;
+            $stop = false;
             $maxPossible = 10; //4096
             $max = ($query instanceof ReadStreamEvents) ? $query->getMaxCount() : self::POSITION_LATEST;

@@ -559,7 +560,8 @@ class EventStore
                     return Observable::of($event);
                 })
                 // If more data is needed do another query
-                ->doOnNext(function (ReadStreamEventsCompleted $event) use ($query, $correlationID, &$end, &$asked, $max, $maxPossible, $messageType) {
+                ->doOnNext(function (ReadStreamEventsCompleted $event) use ($query, $correlationID, &$end, &$stop, &$asked, $max, $maxPossible, $messageType) {
+                   $stope = $end;
                     $records = $event->getEvents();
                     $asked -= count($records);
                     if ($event->getIsEndOfStream()) {
@@ -567,7 +569,7 @@ class EventStore
                     } elseif ($asked <= 0 && $max != self::POSITION_LATEST) {
                         $end = true;
                     }
-                    if (!$end) {
+                    if (!$stop && count($records) > 0) {
                         $start = $records[count($records) - 1];
                         /* @var ResolvedIndexedEvent $start */

@@ -589,8 +591,8 @@ class EventStore
                     }
                 })
                 // Continue to watch until we have all our results (or end)
-                ->takeWhile(function () use (&$end) {
-                    return !$end;
+                ->takeWhile(function () use (&$stop) {
+                    return !$stop;
                 })
                 // Format EventRecord for easy reading
                 ->flatMap(function (ReadStreamEventsCompleted $event) use (&$asked, &$end) {
@@ -608,4 +610,4 @@ class EventStore
                 ->subscribe($observer);
         });
     }
-}
\ No newline at end of file
+}
```

**Comment by Vinceveve** [comment]
Thanks for the bug report perfect to fix :)
I've used an other method and do a fix to keep event in correct order

**Comment by callistino** [comment]
I still see an issue here when try to do anything after a `readForward`, the observable never ends in this case so it's stuck on an infinite loop. It's very simple to prove by subscribing to the observable and trying to do anything on the subscribe.

In the snippet below, the "Read: " echo inside the subscription never executes.

```php
            $eventStore
                ->readEventsForward('domain-test.fr')
                ->do(function (\Rxnet\EventStore\EventRecord $record) {
                    echo "received {$record->getId()}  {$record->getNumber()}@{$record->getStreamId()} {$record->getType()} created at {$record->getCreated()->format('c')}\n";
                })
                ->toArray()
                ->subscribe(
                    function (array $records) {
                        echo 'Read: ' . count($records) . " events.\n";
                    }
                );
```

**Comment by Vinceveve** [comment]
fixed for real in release 2.2.2 thanks for the report :)

**Comment by callistino** [comment]
Shouldn't the PHP requirement be `"php":"^7.0.0"`?

**Comment by Vinceveve** [comment]
Oooops you're right ! just changed

**Comment by callistino** [comment]
@Vinceveve I appreciate your fast responses and your work done on this library. The lates solution is beautiful and I'm learning a lot from it  and from the library about many different architectures. 

With that said, I still have an issue with the latest solution. I'll try to explain my use case to see if we can replicate in an example and get this done once for all.

I need to write a given number of events and then read them. This chain of operations could go on as much as I want. Here is another crude example of what I'm trying to achieve:

```php
<?php

use EventLoop\EventLoop;
use Ramsey\Uuid\Uuid;
use Rxnet\EventStore\Data\WriteEventsCompleted;
use Rxnet\EventStore\NewEvent\JsonEvent;

require __DIR__ . '/../vendor/autoload.php';

$eventStore = new \Rxnet\EventStore\EventStore();
$eventStore->connect()
    ->subscribe(
        function () use ($eventStore) {
            echo "connected \n";
            $write5 = \Rx\Observable::range(0, 5)
                ->flatMap(
                    function () use ($eventStore) {
                        echo 'Write: ';

                        return $eventStore->write('domain-test.fr', [
                            new JsonEvent('/truc/chose', ['id' => Uuid::uuid4()]),
                        ]);
                    }
                )
                ->flatMap(
                    function (WriteEventsCompleted $eventsCompleted) {
                        echo "Last event number {$eventsCompleted->getLastEventNumber()} on commit position {$eventsCompleted->getCommitPosition()} \n";

                        return \Rx\Observable::of($eventsCompleted);
                    }
                )
                // Wait for all writes
                ->toArray()
                ->do(
                    function (array $eventsCompleted) {
                        echo 'Wrote: ' . count($eventsCompleted) . " events.\n";
                    }
                );

            $readAll = $eventStore->readEventsForward('domain-test.fr')
                ->do(
                    function (\Rxnet\EventStore\EventRecord $record) {
                        echo "received {$record->getId()}  {$record->getNumber()}@{$record->getStreamId()} {$record->getType()} created at {$record->getCreated()->format('c')}\n";
                    }
                )
                // Wait for all reads
                ->toArray()
                ->do(
                    function (array $records) {
                        echo 'Read: ' . count($records) . " events.\n";
                    }
                );

            $readAll
                ->concatMapTo($write5)
                ->concatMapTo($readAll)
//                ->concatMapTo($readAll)
//                ->concatMapTo($readAll)
//                ->concatMapTo($readAll)
//                ->concatMapTo($readAll)
//                ->concatMapTo($readAll)
//                ->concatMapTo($readAll)
//                ->concatMapTo($readAll)
//            $write5
//                ->concatMapTo($readAll)
                ->subscribe(
                    function () {
                        echo "stopping\n";
                        EventLoop::getLoop()->stop();
                    },
                    function ($e) {
                        echo $e->getMessage();
                    },
                    function () {
                        EventLoop::getLoop()->stop();
                    }
                );


        });

EventLoop::getLoop()->run();
```

Here are some of the issues:

1. If I execute just the `read` I get twice the number of events back to back (in order). Example, if I have 20 events, I'll get something like this:

```bash
php examples/writeAndRead.php
connected
received 617bb337e5094075a10b45fc53091ad5  0@domain-test.fr /truc/chose created at 2018-07-21T00:19:50+00:00
...
received c276bc175bf14644bc8b848394ee40df  19@domain-test.fr /truc/chose created at 2018-07-23T13:17:19+00:00
received 617bb337e5094075a10b45fc53091ad5  0@domain-test.fr /truc/chose created at 2018-07-21T00:19:50+00:00
...
received c276bc175bf14644bc8b848394ee40df  19@domain-test.fr /truc/chose created at 2018-07-23T13:17:19+00:00
Read: 40 events.
stopping
```

2. Next, if I try to concat 2 reads I get the same result as before, reads 40 events, but the second read reads nothing:
```bash
php examples/writeAndRead.php
connected
...
Read: 40 events.
Read: 0 events.
stopping
```

3. If I write then read It reads nothing:
```bash
php examples/writeAndRead.php
connected
Write: Write: Write: Last event number 20 on commit position 218579624
Write: Last event number 21 on commit position 218579786
Last event number 22 on commit position 218579948
Write: Last event number 23 on commit position 218580110
Last event number 24 on commit position 218580272
Wrote: 5 events.
Read: 0 events.
stopping
```

All other combinations have issues. Again, I may be using the library wrong and any help is appreciated but, I was able to use a custom version of the method `\Rxnet\EventStore\EventStore::readEvents` shown below and everything works perfectly for my use case.

```php
    protected function readEvents(Message $query, $messageType)
    {
        // TODO backpressure, wait for event's array to be readed completely before asking for more in stream
        // OnDemand ? onBackpressureBuffer ?
        return Observable::create(function (ObserverInterface $observer) use ($messageType, $query) {

            $end = false;
            $page = 0;
            $pageSize = 10;
            $offset = ($query instanceof ReadStreamEvents) ? $query->getFromEventNumber() : 0;
            $count = ($query instanceof ReadStreamEvents) ? $query->getMaxCount() : self::POSITION_LATEST;
            $total = self::POSITION_LATEST;

            $query->setMaxCount($count);
            if ($count >= $pageSize) {
                $query->setMaxCount($pageSize);
            }

            $correlationID = $this->writer->createUUIDIfNeeded();

            $this->writer->composeAndWrite($messageType, $query, $correlationID)
                // When written wait for all responses
                ->merge($this->readBuffer->waitFor($correlationID, -1))
                ->do(function () use ($messageType, $correlationID, $query, &$page, $pageSize, $offset, $count) {
                    $page++;
                    $newQuery = clone $query;

                    if ($messageType == MessageType::READ_STREAM_EVENTS_FORWARD) {
                        $newQuery->setFromEventNumber($offset + ($page * $pageSize));
                    } else {
                        $newQuery->setFromEventNumber($offset - ($page * $pageSize));
                    }

                    if (($newQuery->getFromEventNumber() + $pageSize) > ($offset + $count)) {
                        $newQuery->setMaxCount(($newQuery->getFromEventNumber() + $pageSize) - ($offset + $count));
                    }

                    $this->writer->composeAndWrite($messageType, $newQuery, $correlationID);
                })
                ->takeWhile(function () use (&$end) {
                    return !$end;
                })
                // Throw if we have an error message
                ->do(function (ReadStreamEventsCompleted $event) {
                    if ($error = $event->getError()) {
                        throw new \Exception($error);
                    }
                })
                // Save current total events.
                ->do(function (ReadStreamEventsCompleted $event) use (&$total) {
                    $total = $event->getLastEventNumber();
                })
                // Format EventRecord for easy reading
                ->concatMap(function (ReadStreamEventsCompleted $event) use (&$end, &$total, $offset, $page, $pageSize, $count) {
                    $end = $event->getIsEndOfStream() || $event->getNextEventNumber() >= $total || ($offset + ($page * $pageSize) > ($offset + $count));

                    /* @var ReadStreamEventsCompleted $event */
                    $records = [];
                    /* @var \Rxnet\EventStore\EventRecord[] $records */
                    $events = $event->getEvents();
                    foreach ($events as $item) {
                        /* @var \Rxnet\EventStore\Data\ResolvedIndexedEvent $item */
                        $records[] = new EventRecord($item->getEvent());
                    }

                    return Observable::fromArray($records);
                })
                ->subscribe($observer);

        });
    }
```
